# Generated by Django 3.0.1 on 2019-12-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='marathon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Marathon'),
        ),
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Movie'),
        ),
    ]
