# Generated by Django 3.0.1 on 2019-12-30 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0002_auto_20191230_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='occupied_seats',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
