# Generated by Django 3.0.1 on 2020-02-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20200108_2035'),
        ('screenings', '0006_auto_20200215_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='marathon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show', to='shows.Marathon'),
        ),
    ]
