# Generated by Django 3.0.1 on 2020-09-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0007_auto_20200215_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_scheme',
        ),
    ]
