# Generated by Django 3.0.1 on 2020-09-15 22:03

from django.db import migrations, models
import screenings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0008_remove_room_room_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='occupied_seats',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True, validators=[screenings.validators.validate_positive_integers_list]),
        ),
    ]
