# Generated by Django 3.0.1 on 2019-12-30 14:07

from django.db import migrations, models
import informations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('anwser', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_posted', models.DateField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=informations.models.news_directory_path)),
                ('title', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=250)),
                ('description_html', models.FileField(blank=True, null=True, upload_to=informations.models.news_directory_path)),
            ],
        ),
    ]
