# Generated by Django 3.0.1 on 2020-01-08 19:35

import django.core.validators
from django.db import migrations, models
import informations.models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_auto_20200108_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=informations.models.news_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
