# Generated by Django 3.0.1 on 2020-01-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_faq_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='number',
        ),
    ]
