# Generated by Django 3.0.1 on 2020-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_remove_faq_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
