# Generated by Django 3.0.1 on 2020-01-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0006_faq_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='FAQs',
        ),
    ]
