# Generated by Django 3.0.1 on 2021-02-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0010_auto_20210216_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_description',
            field=models.TextField(blank=True, max_length=3500, null=True),
        ),
    ]
