# Generated by Django 4.1.3 on 2023-02-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0012_auto_20210217_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='anwser',
            new_name='answer',
        ),
    ]
