# Generated by Django 4.1.3 on 2023-02-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0013_rename_anwser_faqs_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='day_posted',
            field=models.DateField(null=True),
        ),
    ]
