# Generated by Django 4.1.3 on 2023-02-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0015_alter_news_day_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='day_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
