# Generated by Django 4.1.3 on 2023-02-21 09:46

import django.core.validators
from django.db import migrations, models
import informations.models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0018_alter_news_day_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=informations.models.news_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'webp'])]),
        ),
    ]
