# Generated by Django 3.0.1 on 2020-02-15 15:11

from django.db import migrations
import shows.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20200108_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=shows.models.thumbnail_image_directory_path),
        ),
    ]
