# Generated by Django 3.0.1 on 2020-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20200218_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tt'),
        ),
    ]
