# Generated by Django 3.0.1 on 2019-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
