# Generated by Django 3.0.1 on 2020-11-22 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_components', '0003_remove_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membershipment', to=settings.AUTH_USER_MODEL),
        ),
    ]
