# Generated by Django 3.0.1 on 2020-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0005_auto_20201122_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('ST', 'Standard'), ('GO', 'Gold')], default='ST', max_length=2),
            preserve_default=False,
        ),
    ]
