# Generated by Django 3.0.1 on 2020-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0007_auto_20201122_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
