# Generated by Django 3.0.1 on 2020-12-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0008_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
