# Generated by Django 3.0.1 on 2021-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_components', '0009_auto_20201220_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bulk_create',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
