# Generated by Django 3.0.1 on 2020-01-08 19:35

import django.core.validators
from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20200108_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=shows.models.image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=shows.models.marathon_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_image',
            field=models.FileField(upload_to=shows.models.main_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
