# Generated by Django 3.0.1 on 2020-03-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
