# Generated by Django 3.0.1 on 2020-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_movie_main_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_trailer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_url',
            field=models.CharField(max_length=1000),
        ),
    ]
