# Generated by Django 3.0.1 on 2020-04-27 17:13

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20200410_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathon',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='marathon',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=shows.models.thumbnail_image_directory_path),
        ),
    ]
