# Generated by Django 3.0.1 on 2020-04-27 17:32

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20200427_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=shows.models.marathon_thumbnail_directory_path),
        ),
    ]
