# Generated by Django 3.0.1 on 2020-04-27 17:34

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_auto_20200427_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=shows.models.thumbnail_image_directory_path),
        ),
    ]
