# Generated by Django 3.0.1 on 2020-05-11 14:49

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_auto_20200427_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=shows.models.main_trailer_directory_path),
        ),
    ]
