# Generated by Django 3.0.1 on 2020-05-11 15:33

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_movie_trailer_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='trailer_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=shows.models.trailer_directory_path),
        ),
    ]
