# Generated by Django 3.0.1 on 2020-05-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_trailer_trailer_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='trailer_url',
            new_name='trailer',
        ),
    ]
