# Generated by Django 3.0.1 on 2020-07-18 16:20

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_auto_20200511_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=shows.models.image_thumbnail_directory_path),
        ),
    ]
