# Generated by Django 3.0.1 on 2020-07-18 16:30

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=shows.models.image_thumbnail_directory_path),
        ),
    ]
