# Generated by Django 3.0.1 on 2020-09-15 20:55

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_auto_20200719_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=shows.models.image_thumbnail_directory_path),
        ),
    ]
