# Generated by Django 4.1.3 on 2023-01-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0020_auto_20200915_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathon',
            old_name='description_html',
            new_name='description',
        ),
    ]
