# Generated by Django 4.1.3 on 2023-01-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0022_alter_marathon_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathon',
            old_name='title',
            new_name='name',
        ),
    ]
