# Generated by Django 4.1.3 on 2023-02-06 05:14

import django.core.validators
from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0025_rename_relese_date_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_image',
            field=models.FileField(upload_to=shows.models.main_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'webp'])]),
        ),
    ]
