# Generated by Django 4.1.3 on 2023-02-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0028_marathon_slug_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=400, null=True),
        ),
    ]
