# Generated by Django 4.1.3 on 2023-02-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0029_alter_marathon_slug_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='short_description',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.CharField(max_length=350),
        ),
    ]
